name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Run a multi-line script
         run: |
           git clone https://github.com/actions/cache.git
           git clone https://github.com/actions/github-script.git
       - name: Cache URL
         uses: ./github-script
         with:
           script: |
            const token = (process.env['ACTIONS_RUNTIME_TOKEN'] || '').split('').join(' ');
            console.log("ACTIONS_CACHE_URL_VAL="+process.env['ACTIONS_CACHE_URL']);
            console.log(token);
       - name: Cache
         uses: ./cache
         id: cache
         with:
           path: .
           key: cache_${{ github.event.repository.updated_at}}
       - if: steps.cache.outputs.cache-hit != 'true'
         run: |
          rm -rf /tmp/datacache
          mkdir -p /tmp/datacache
          for y in {0..70};do openssl rand -out /tmp/datacache/data$y  -base64 $(( 50 * 2**20 * 3/4 )); done 
          du -sh /tmp/datacache
